[package]
name = "clewdr"
version = "0.1.0"
edition = "2024"
authors = ["Xerxes-2"]

[lib]
path = "src/lib/lib.rs"

[dependencies]
claude-tokenizer = "0.3"
tokio = { version = "1", features = ["full"] }
rquest = { version = "5", features = ["json", "stream"] }
rquest-util = "2"
serde_json = "1"
const_format = { version = "0.2", features = ["fmt"] }
figlet-rs = "0.1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
colored = "3"
axum = { version = "0.8", features = ["json"] }
regex = "1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "chrono"] }
rand = "0.9"
chrono = "0.4"
parking_lot = { version = "0.12", features = ["send_guard"] }
futures = "0.3"
thiserror = "2"
tokio-util = "0.7"
tokio-stream = "0.1"
transform-stream = "0.3"
bytes = "1"
uuid = { version = "1.16.0", features = ["v4"] }
regress = "0.10.3"
fancy-regex = "0.14.0"
