[package]
name = "clewdr"
version = "0.1.0"
edition = "2024"
authors = ["Xerxes-2"]

[lib]
path = "src/lib/lib.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
rquest = { version = "5", features = ["json", "stream", "multipart"] }
rquest-util = "2"
serde_json = "1"
const_format = { version = "0.2", features = ["fmt"] }
figlet-rs = "0.1"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
colored = "3"
axum = { version = "0.8", features = [
    "json",
    "tracing",
    "tokio",
    "macros",
    "http2",
] }
regex = "1"
tracing = { version = "0.1", features = [
    "max_level_debug",
    "release_max_level_warn",
] }
tracing-subscriber = { version = "0.3", features = ["env-filter", "chrono"] }
rand = "0.9"
chrono = "0.4"
parking_lot = { version = "0.12", features = ["send_guard"] }
futures = "0.3"
thiserror = "2"
uuid = { version = "1", features = ["v4"] }
tower-http = { version = "0.6", features = ["trace"] }
clap = { version = "4", features = ["derive"] }
async-trait = "0.1"
futures-util = "0.3"
base64 = "0.22.1"
