cookie = ""
cookie_array = []
wasted_cookie = []
unknown_models = []
cookie_counter = 3
cookie_index = 0
proxy_password = ""
ip = "0.0.0.0"
port = 8484
local_tunnel = false
buffer_size = 1
system_interval = 3
rproxy = ""
api_rproxy = ""
placeholder_token = ""
placeholder_byte = ""
prompt_experiment_first = ""
prompt_experiment_next = ""
personality_format = "{{char}}'s personality: {{personality}}"
scenario_format = "Dialogue scenario: {{scenario}}"

[settings]
renew_always = true
retry_regenerate = false
prompt_experiments = true
system_experiments = true
prevent_imperson = true
all_samples = false
no_samples = false
strip_assistant = false
strip_human = false
pass_params = false
clear_flags = true
preserve_chats = false
log_messages = true
full_colon = true
padtxt = "0,0,0"
xml_plot = true
skip_restricted = false
artifacts = false
superfetch = true
