# language:dev-build.txt

name: 我不知道

on:
  push:
    tags: # 触发条件改为推送 tag
      - 'v*' # 匹配 v 开头的 tag，例如 v1.0, v2.3.4
  workflow_dispatch: # 保留手动触发

# 添加权限以允许创建 Release 和上传资源
permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  linux:
    name: Build Linux (GNU)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64
            target_triple: x86_64-unknown-linux-gnu
            apt_packages: ""
            custom_env: {}
          - target: aarch64
            target_triple: aarch64-unknown-linux-gnu
            apt_packages: crossbuild-essential-arm64
            custom_env:
              CFLAGS_aarch64_unknown_linux_gnu: -D__ARM_ARCH=8
              CC: aarch64-linux-gnu-gcc
              CXX: aarch64-linux-gnu-g++
              CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-g++
              RUSTC_LINKER: aarch64-linux-gnu-g++

    steps:
      - uses: actions/checkout@v4

      - name: Install base dependencies on Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake perl pkg-config libclang-dev musl-tools

      - name: Install target-specific APT dependencies
        if: ${{ matrix.apt_packages != '' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.apt_packages }}

      - name: Add Rust target
        run: rustup target add ${{ matrix.target_triple }}

      - uses: Swatinem/rust-cache@v2

      - name: Build for ${{ matrix.target }}
        env: ${{ matrix.custom_env }}
        run: cargo build --release --target ${{ matrix.target_triple }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: clewdr-linux-${{ matrix.target }}
          path: target/${{ matrix.target_triple }}/release/clewdr
          retention-days: 1

  android:
    name: Build Android (NDK)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: aarch64
            target_triple: aarch64-linux-android
            apt_packages: ""

    steps:
      - uses: actions/checkout@v4
      - uses: nttld/setup-ndk@v1.5.0
        id: setup-ndk
        with:
          ndk-version: r27c
          add-to-path: true

      - name: Install base dependencies on Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake perl pkg-config libclang-dev musl-tools

      - name: Install target-specific APT dependencies
        if: ${{ matrix.apt_packages != '' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.apt_packages }}

      - name: Add Rust target
        run: rustup target add ${{ matrix.target_triple }}

      - uses: Swatinem/rust-cache@v2

      - name: Build for ${{ matrix.target }}
        run: |
          cargo install cargo-ndk
          cargo ndk --target ${{ matrix.target_triple }} build --release
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
          ANDROID_NDK_ROOT: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: clewdr-android-${{ matrix.target }}
          path: |
            target/${{ matrix.target_triple }}/release/clewdr
            $ANDROID_NDK_HOME/toolchains/llvm/prebuilt/linux-x86_64/sysroot/usr/lib/aarch64-linux-android/libc++_shared.so
          retention-days: 1

  musllinux:
    name: Build Linux (musl)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64
            target_triple: x86_64-unknown-linux-musl
            package: x86_64-linux-musl-cross
            apt_packages: ""
            custom_env:
              CC: x86_64-linux-musl-gcc
              CXX: x86_64-linux-musl-g++
              CARGO_TARGET_X86_64_UNKNOWN_LINUX_MUSL_LINKER: x86_64-linux-musl-g++
              RUSTC_LINKER: x86_64-linux-musl-g++
          - target: aarch64
            target_triple: aarch64-unknown-linux-musl
            package: aarch64-linux-musl-cross
            apt_packages: crossbuild-essential-arm64
            custom_env:
              CC: aarch64-linux-musl-gcc
              CXX: aarch64-linux-musl-g++
              CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER: aarch64-linux-musl-g++
              RUSTC_LINKER: aarch64-linux-musl-g++

    steps:
      - uses: actions/checkout@v4

      - name: Install base dependencies on Ubuntu
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake perl pkg-config libclang-dev musl-tools

      - name: Install target-specific APT dependencies
        if: ${{ matrix.apt_packages != '' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.apt_packages }}

      - name: Prepare musl cross-compiler
        run: |
          curl -O http://musl.cc/${{ matrix.package }}.tgz
          tar xzf ${{ matrix.package }}.tgz -C /opt
          echo "/opt/${{ matrix.package }}/bin/" >> $GITHUB_PATH

      - name: Add Rust target
        run: rustup target add ${{ matrix.target_triple }}

      - uses: Swatinem/rust-cache@v2

      - name: Build for ${{ matrix.target }}
        env: ${{ matrix.custom_env }}
        run: cargo build --release --target ${{ matrix.target_triple }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: clewdr-musllinux-${{ matrix.target }}
          path: target/${{ matrix.target_triple }}/release/clewdr
          retention-days: 1

  windows:
    name: Build Windows
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - target: x86_64
            target_triple: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies on Windows
        run: |
          choco install cmake -y
          choco install strawberryperl -y
          choco install pkgconfiglite -y
          choco install llvm -y
          choco install nasm -y
        shell: cmd

      - uses: Swatinem/rust-cache@v2

      - name: Build on Windows with Static Linking
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
        run: cargo build --release --target ${{ matrix.target_triple }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: clewdr-windows-${{ matrix.target }}
          path: target/${{ matrix.target_triple }}/release/clewdr.exe
          retention-days: 1

  macos:
    name: Build macOS
    strategy:
      matrix:
        include:
          - target: x86_64
            runner: macos-latest
            target_triple: x86_64-apple-darwin
          - target: aarch64
            runner: macos-latest
            target_triple: aarch64-apple-darwin
    runs-on: ${{ matrix.runner }}
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies on macOS
        run: |
          brew update
          brew install --formula cmake pkg-config llvm

      - name: Add Rust target
        run: rustup target add ${{ matrix.target_triple }}

      - uses: Swatinem/rust-cache@v2

      - name: Build for ${{ matrix.target }}
        run: cargo build --release --target ${{ matrix.target_triple }}

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: clewdr-macos-${{ matrix.target }}
          path: target/${{ matrix.target_triple }}/release/clewdr
          retention-days: 1

  # 新增 release 作业
  release:
    name: Create GitHub Release
    needs: [linux, android, musllinux, windows, macos] # 依赖所有构建作业
    runs-on: ubuntu-latest
    # 确保只在 tag push 时运行 release 作业
    if: startsWith(github.ref, 'refs/tags/') 
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          # 指定下载所有产物到 'artifacts' 目录
          # 每个产物会下载到其对应的子目录中, 例如 artifacts/clewdr-linux-x86_64/clewdr-linux-x86_64.zip
          path: artifacts 

      - name: Display structure of downloaded files # (可选) 打印下载的文件结构，方便调试
        run: ls -R artifacts

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2 # 使用推荐的 action 来创建 release
        with:
          # action 会自动使用触发工作流的 tag (github.ref)
          # files 指定要上传的资源文件路径，使用通配符匹配所有下载的 zip 文件
          files: artifacts/*/*
          # 可选: 如果你想自动生成 Release Notes（基于 Conventional Commits）
          # generate_release_notes: true 
          # 可选: 如果你想创建 draft release
          # draft: true
          # 可选: 如果你想创建 pre-release
          # prerelease: true
        env:
          # GITHUB_TOKEN 是自动提供的 secret，用于授权 action 操作仓库
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
